root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/cando ./cmd/cando"
  entrypoint = ["./tmp/cando", "web"]
  include_ext = ["go", "yaml", "html", "tmpl", "css", "js"]
  exclude_dir = ["tmp", "conversations", ".git"]
  exclude_file = []
  delay = 1000
  stop_on_error = true
  send_interrupt = true
  kill_delay = 2000

[log]
  main_only = true
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
